dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
script:
  - echo hello > test.ion
  - tools/ion-hash md5 test.ion

